Getting data from coin api...Done
Getting data from COVID19 api...Done
Starting to fetch twitter data...
Processing BTC tweets...Done
Processing ETH tweets...Done
Processing XRP tweets...Done
Processing LTC tweets...Done
Writing to dataset file(../data/dataset.csv)...Done
Current time: 2020-03-20 23:07
Getting data from coin api...Done
Getting data from COVID19 api...Done
Starting to fetch twitter data...
Processing BTC tweets...Done
Processing ETH tweets...Done
Processing XRP tweets...Done
Processing LTC tweets...Done
Writing to dataset file(../data/dataset.csv)...Done
----------------------------------------------------
Current time: 2020-03-24 18:00
Getting data from coin api with key no.1...Done
Getting data from COVID19 api...Done
Starting to fetch twitter data...
Processing BTC tweets...Done
Processing ETH tweets...Done
Processing XRP tweets...Done
Processing LTC tweets...Done
Writing to dataset file(../data/dataset.csv)...Done
----------------------------------------------------
Current time: 2020-03-24 18:12
Getting data from coin api with key no.0...Done
Getting data from COVID19 api...Done
Starting to fetch twitter data...
Processing BTC tweets...Done
Processing ETH tweets...Done
Processing XRP tweets...Traceback (most recent call last):
  File "sensor.py", line 152, in <module>
    if balance['Positive'] > balance['Negative']:
KeyError: 'Negative'
Current time: 2020-03-24 18:21
Getting data from coin api with key no.1...Done
Getting data from COVID19 api...Done
Starting to fetch twitter data...
Processing BTC tweets...Done
Processing ETH tweets...Done
Processing XRP tweets...Done
Processing LTC tweets...Done
Writing to dataset file(../data/dataset.csv)...Done
----------------------------------------------------
Traceback (most recent call last):
  File "sensor.py", line 188, in <module>
    client.create_data(ADAFRUIT_FEED_ID, data)
AttributeError: 'MQTTClient' object has no attribute 'create_data'
Current time: 2020-03-24 18:41
Getting data from coin api with key no.0...Traceback (most recent call last):
  File "sensor.py", line 115, in <module>
    dict[f"{coin}_PRICE_USD"] = float((res.json())["rate"])
KeyError: 'rate'
Current time: 2020-03-24 18:45
Getting data from coin api with key no.1...Traceback (most recent call last):
  File "sensor.py", line 115, in <module>
    print(f"Response: {res.read()}")
AttributeError: 'Response' object has no attribute 'read'
Current time: 2020-03-24 18:45
Getting data from coin api with key no.0...Response: <Response [403]>
Traceback (most recent call last):
  File "sensor.py", line 116, in <module>
    dict[f"{coin}_PRICE_USD"] = float((res.json())["rate"])
KeyError: 'rate'
Current time: 2020-03-24 18:48
Getting data from coin api with key no.1...Response: <Response [403]>
Traceback (most recent call last):
  File "sensor.py", line 116, in <module>
    dict[f"{coin}_PRICE_USD"] = float((res.json())["rate"])
KeyError: 'rate'
Current time: 2020-03-24 18:49
Getting data from coin api with key no.1...Response: <Response [403]>
Traceback (most recent call last):
  File "sensor.py", line 116, in <module>
    dict[f"{coin}_PRICE_USD"] = float((res.json())["rate"])
KeyError: 'rate'
Current time: 2020-03-24 18:50
Getting data from coin api with key no.0...Traceback (most recent call last):
  File "sensor.py", line 115, in <module>
    print(f"Response: {res['text']}")
TypeError: 'Response' object is not subscriptable
Current time: 2020-03-24 18:51
Getting data from coin api with key no.1...Response: {'error': 'Forbidden - Your API key dont have enough privileges to access this resource. (status_id: BANNED_FREE_PLAN_IP_ABUSE)'}
Traceback (most recent call last):
  File "sensor.py", line 116, in <module>
    dict[f"{coin}_PRICE_USD"] = float((res.json())["rate"])
KeyError: 'rate'
